### ISSUE TITLE
Contributing to Menagerie

### ISSUE THREAD

**Issue by kevinzakka** [lvjonok/atlas-mujoco#1]
Hi @lvjonok, would you be down to add this to [MuJoCo Menagerie](https://github.com/google-deepmind/mujoco_menagerie)?

**Comment by lvjonok** [comment]
Yes, sure. I will create a PR soon. 

Also, I would be glad to accept any help with texture mappings, because despite there are [textures](https://github.com/RobotLocomotion/drake/tree/73a8da32cd41ff7fd023c3680f8250860cbd0e6b/examples/atlas/urdf/materials/textures) for meshes, I wasn't able to map them correctly for greater visualization.

**Comment by kevinzakka** [comment]
Awesome! I can take a look at the textures once you have a PR ready.

**Comment by lvjonok** [comment]
PR is added [here](https://github.com/google-deepmind/mujoco_menagerie/pull/25)
